[package]
name = "idle-manager-update"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
idle-manager-core.workspace = true
minisign-verify.workspace = true
thiserror.workspace = true
tracing.workspace = true
velopack.workspace = true

[lints]
workspace = true
